version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@babel/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "babel-preset-expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@react-native/jest-preset"
      - dependency-name: "react-native-screens"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

